spring.cloud.config.label=master
spring.application.name=jonasandersen-admin
spring.jpa.open-in-view=false
spring.threads.virtual.enabled=true
spring.mvc.hiddenmethod.filter.enabled=true

management.endpoints.web.exposure.include=health,info,prometheus
management.metrics.tags.application=${spring.application.name}

spring.datasource.hikari.maximum-pool-size=5
spring.jpa.hibernate.ddl-auto=validate

spring.web.error.include-message=always
spring.web.error.include-stacktrace=never
spring.docker.compose.enabled=false
loki.url = https://loki.jonasandersen.dev/loki/api/v1/push