jonasandersen.admin.features.linode-stub=false
loki.url = http://five.tailscale.svc.cluster.local:3100/loki/api/v1/push
spring.config.import=optional:configserver:http://config-server-service.common.svc.cluster.local:8888