name: Run tests on pull requests

on:
  merge_group:
  pull_request:
    branches:
      - master

concurrency:
  cancel-in-progress: true
  group: pr-${{ github.event.pull_request.number }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.20.0
        with:
          java-version: 26
          java-distribution: liberica
          checkout-persist-credentials: true
          cache-prefix: ${{ runner.arch }}
          settings-servers: |
            [{
                "id": "reposilite-releases",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            },
            {
                "id": "reposilite-snapshots",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            }]

      - name: Run unit tests
        run: mvn clean test -T 1C

  itest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.20.0
        with:
          java-version: 26
          java-distribution: liberica
          checkout-persist-credentials: true
          cache-prefix: ${{ runner.arch }}
          settings-servers: |
            [{
                "id": "reposilite-releases",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            },
            {
                "id": "reposilite-snapshots",
                "username": "${{ secrets.REPOSILITE_USERNAME }}",
                "password": "${{ secrets.REPOSILITE_PASSWORD }}"
            }]

      - name: Run integration tests
        run: mvn test-compile surefire:test@integration-tests -T 1C

